name: CD 

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull nikin2204/first_container:latest
    - name: Delete Old docker container
      run: sudo docker rm -f first_container-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name first_container-container nikin2204/first_container